import { Kanit as KanitFont } from "next/font/google";
import "@/app/globals.css";
export const metadata = {
    title: "Crownset website",
    description: "Generated by create next app",
  };

  const kanit = KanitFont({
    subsets: ["latin"],
    weight: ["300"],
  });
  
export default function AuthLayout({ children }) {
    return (
        <html className={kanit.className}>
      <body className={kanit.className}>
        
        {children}
        
      </body>
    </html>
          
    )
}