import { Kanit as KanitFont } from "next/font/google";
import "@/app/globals.css";
import AdminDashboard from "@/components/AdminDashboard";
export const metadata = {
    title: "Crownset website",
    description: "Generated by create next app",
};

const kanit = KanitFont({
    subsets: ["latin"],
    weight: ["300"],
});

export default function AuthLayout({ children }) {
    return (
        <html className={kanit.className}>
            <body className={kanit.className}> 
                <AdminDashboard />
                <div className="pt-16 pl-0 md:pl-64 transition-all duration-300 ease-in-out">
                    {children}
                </div>
            </body>
        </html>

    )
}