export const openNav_icon = require("../assets/images/openNav.png")
export const closeNav_icon = require("../assets/images/close.png")
export const divider = require("../assets/images/dividerline.png")
export const location_icon = require("../assets/images/google-maps.png")
export const homeone = require("../assets/images/homeone.png");
export const hometwo = require("../assets/images/hometwo.png");
export const curveline = require("../assets/images/curveline.png");
// export const garvit = require("../assets/images/garvitsirfinal.png");
export const priyam = require("../assets/images/priyamsirfinal.png")
export const amazon_logo = require("../assets/images/amazomvector.png")
export const boat_logo = require("../assets/images/boatvector.png")
export const haldirams_logo  = require("../assets/images/haldiramsvector.png")
export const hyundai_logo  = require("../assets/images/hyundaivector.png")
export const kfc_logo  = require("../assets/images/kfcvector.png")
export const lv_logo  = require("../assets/images/lvvector.png")
export const benz_logo  = require("../assets/images/mbvector.png")
export const nestle_logo  = require("../assets/images/nestlevector.png")
export const netflix_logo  = require("../assets/images/netflixvector.png")
export const nike_logo  = require("../assets/images/nikevector.png")
export const serviceimg2 = require("../assets/images/serviceimg2.jpg")
export const aboutimg1 = require("../assets/images/aboutimg1.png");
export const aboutimg2 = require("../assets/images/aboutimg2.jpg");
export const transperancy = require("../assets/images/transparency.png");
export const team = require("../assets/images/team.jpg");
export const result = require("../assets/images/result.png");
export const serviceimg1 = require("../assets/images/serviceimg1.png");
export const award = require("../assets/images/award.webp");
export const homeimg = require("../assets/images/img1.jpg");
export const logo = require("../assets/images/logo.png");
export const crownsetLogo = require("../assets/images/croensetLogo2.png")


